name: basic
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: mkdir build && cmake -B build -S . && cmake --build build
      - name: Run benchmarks
        run: |
          cd build
          ./benchmark_my_add
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            build/main
            build/tests
            

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x tests && ./tests

  run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x main && ./main 4 5
        
  doxygen:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        # - name: Install Doxygen
          # run: sudo apt-get install doxygen
        - name: Doxygen Action
          uses: mattnotmitt/doxygen-action@1.9.8
          with:
            # Path to Doxyfile
            doxyfile-path: "./Doxyfile" # default is ./Doxyfile
            # Working directory
            working-directory: "." # default is .
   
        # - name: Generate documentation
          # run: doxygen Doxyfile

        - name: Deploy to GitHub Pages
          # run: touch .nojekyll
          uses: peaceiris/actions-gh-pages@v4
          with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}          
            publish_dir: ./html
